### ISSUE TITLE
Rubygems version is a bit old

### ISSUE THREAD

**Issue by methodmissing** [benchmark-driver/benchmark-driver#60]
Hi,

I noticed the rubygems version is circa 2018 and is missing many features from mainline. Any chance latest could be pushed there too?

Best,
Lourens

**Comment by k0kubun** [comment]
The version tags have been always pushed to rubygems.org shortly and I can see 2019 versions in https://rubygems.org/gems/benchmark_driver:

<img width="983" alt="Screen Shot 2019-09-22 at 6 49 41" src="https://user-images.githubusercontent.com/3138447/65388914-35480c80-dd05-11e9-86db-6f601656b39a.png">

Therefore I completely don't understand your problem. Please explain more about what's missing on your side.

**Comment by k0kubun** [comment]
Or perhaps you're seeing https://rubygems.org/gems/benchmark-driver? It's just an alias which should work forever without updates there.

**Comment by methodmissing** [comment]
My bad, gem install benchmark-driver installed the latest 2018 version -
perhaps a bug with aliases and installing latest versions

**Comment by k0kubun** [comment]
```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
$ gem -v
3.0.3
$ gem list | grep benchmark
$ gem install benchmark-driver
Fetching benchmark_driver-0.15.6.gem
Fetching benchmark-driver-0.1.0.gem
Successfully installed benchmark_driver-0.15.6
Successfully installed benchmark-driver-0.1.0
Parsing documentation for benchmark_driver-0.15.6
Installing ri documentation for benchmark_driver-0.15.6
Parsing documentation for benchmark-driver-0.1.0
Installing ri documentation for benchmark-driver-0.1.0
Done installing documentation for benchmark_driver, benchmark-driver after 0 seconds
2 gems installed
```

I don't think there's a bug in aliases either. benchmark-driver.gem relies on benchmark_driver.gem >= 0. At least I don't see anything to be fixed in benchmark-driver.gem.

Please report it to https://github.com/rubygems/rubygems/issues/new instead, if you find something in your rubygems installation.
